"""initial_schema

Revision ID: 1010165eabfa
Revises: 
Create Date: 2026-07-20 18:45:17.053393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1010165eabfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('default_config', sa.JSON(), nullable=False),
    sa.Column('supports_tier', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('billing_status', sa.String(length=20), nullable=False),
    sa.Column('billing_plan', sa.String(length=20), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('max_sites', sa.Integer(), nullable=False),
    sa.Column('max_panels', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('data_retention_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('store_code', sa.String(length=40), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'store_code', name='uq_tenant_storecode')
    )
    op.create_index('ix_sites_tenant', 'sites', ['tenant_id'], unique=False)
    op.create_table('tenant_themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('primary_color', sa.String(length=10), nullable=False),
    sa.Column('secondary_color', sa.String(length=10), nullable=False),
    sa.Column('accent_color', sa.String(length=10), nullable=False),
    sa.Column('background_color', sa.String(length=10), nullable=False),
    sa.Column('surface_color', sa.String(length=10), nullable=False),
    sa.Column('text_color', sa.String(length=10), nullable=False),
    sa.Column('font_family', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('dark_mode_default', sa.Boolean(), nullable=False),
    sa.Column('layout_preset', sa.String(length=20), nullable=False),
    sa.Column('panel_border_radius', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('usage_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('active_sites', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('total_panels', sa.Integer(), nullable=False),
    sa.Column('records_ingested', sa.BigInteger(), nullable=False),
    sa.Column('storage_mb', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'snapshot_date', name='uq_usage_tenant_date')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_role')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_tenant_email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_date', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_tenant', 'audit_log', ['tenant_id'], unique=False)
    op.create_table('dashboard_panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('panel_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('role_access', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['panel_type_id'], ['panel_types.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_panels_tenant', 'dashboard_panels', ['tenant_id'], unique=False)
    op.create_table('data_watermarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('last_sequence_id', sa.Integer(), nullable=True),
    sa.Column('last_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'tier', name='uq_watermark_site_tier')
    )
    op.create_table('ej_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ej_header_id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('register_number', sa.Integer(), nullable=False),
    sa.Column('transaction_number', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('ej_header_type_id', sa.Integer(), nullable=False),
    sa.Column('ej_header_type', sa.String(length=30), nullable=False),
    sa.Column('is_finalised', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('is_no_sale', sa.Boolean(), nullable=False),
    sa.Column('is_on_hold', sa.Boolean(), nullable=False),
    sa.Column('sale_total', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('rounding', sa.Float(), nullable=False),
    sa.Column('clerk_number', sa.Integer(), nullable=False),
    sa.Column('clerk_name', sa.String(length=30), nullable=False),
    sa.Column('clerk_shift_id', sa.Integer(), nullable=False),
    sa.Column('training_mode', sa.Boolean(), nullable=False),
    sa.Column('receipt_reference', sa.String(length=15), nullable=True),
    sa.Column('transaction_identifier', sa.String(length=40), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'ej_header_id', name='uq_ej_header_site')
    )
    op.create_index('ix_ej_trans_date', 'ej_transactions', ['transaction_date'], unique=False)
    op.create_index('ix_ej_trans_site', 'ej_transactions', ['site_id'], unique=False)
    op.create_index('ix_ej_trans_tenant', 'ej_transactions', ['tenant_id'], unique=False)
    op.create_index('ix_ej_trans_type', 'ej_transactions', ['ej_header_type_id'], unique=False)
    op.create_table('site_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('site_daily_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('gross_sales_inc', sa.Float(), nullable=False),
    sa.Column('gross_sales_ex', sa.Float(), nullable=False),
    sa.Column('nett_sales_inc', sa.Float(), nullable=False),
    sa.Column('nett_sales_ex', sa.Float(), nullable=False),
    sa.Column('gst_total', sa.Float(), nullable=False),
    sa.Column('total_cost_ex', sa.Float(), nullable=False),
    sa.Column('total_profit_ex', sa.Float(), nullable=False),
    sa.Column('total_discounts', sa.Float(), nullable=False),
    sa.Column('total_markdowns', sa.Float(), nullable=False),
    sa.Column('loyalty_points', sa.Float(), nullable=False),
    sa.Column('cancel_count', sa.Integer(), nullable=False),
    sa.Column('no_sale_count', sa.Integer(), nullable=False),
    sa.Column('void_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'summary_date', name='uq_summary_site_date')
    )
    op.create_index('ix_summary_date', 'site_daily_summaries', ['summary_date'], unique=False)
    op.create_index('ix_summary_site', 'site_daily_summaries', ['site_id'], unique=False)
    op.create_index('ix_summary_tenant', 'site_daily_summaries', ['tenant_id'], unique=False)
    op.create_table('site_heartbeats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('records_sent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heartbeats_lastseen', 'site_heartbeats', ['last_seen_at'], unique=False)
    op.create_index('ix_heartbeats_site_tier', 'site_heartbeats', ['site_id', 'tier'], unique=False)
    op.create_table('site_hourly_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('hour_date', sa.DateTime(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('nett_sales_inc', sa.Float(), nullable=False),
    sa.Column('customer_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'hour_date', name='uq_hourly_site_date')
    )
    op.create_index('ix_hourly_tenant', 'site_hourly_summaries', ['tenant_id'], unique=False)
    op.create_table('ej_discounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ej_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('ej_discount_object_id', sa.Integer(), nullable=False),
    sa.Column('ej_detail_id', sa.Integer(), nullable=False),
    sa.Column('ej_plu_object_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=False),
    sa.Column('discount_type_id', sa.Integer(), nullable=False),
    sa.Column('discount_scope_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('discount_number', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ej_transaction_id'], ['ej_transactions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'ej_discount_object_id', name='uq_ej_disc_site')
    )
    op.create_index('ix_ej_disc_tenant', 'ej_discounts', ['tenant_id'], unique=False)
    op.create_index('ix_ej_disc_trans', 'ej_discounts', ['ej_transaction_id'], unique=False)
    op.create_table('ej_line_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ej_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('ej_plu_object_id', sa.Integer(), nullable=False),
    sa.Column('ej_detail_id', sa.Integer(), nullable=False),
    sa.Column('entry_sequence', sa.Integer(), nullable=False),
    sa.Column('plu', sa.String(length=18), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=32), nullable=True),
    sa.Column('caption', sa.String(length=25), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('nett_amount_inc', sa.Float(), nullable=False),
    sa.Column('gross_amount_inc', sa.Float(), nullable=False),
    sa.Column('nett_amount_ex', sa.Float(), nullable=False),
    sa.Column('gross_amount_ex', sa.Float(), nullable=False),
    sa.Column('gross_gst_amount', sa.Float(), nullable=False),
    sa.Column('nett_gst_amount', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('department_number', sa.Integer(), nullable=False),
    sa.Column('department_description', sa.String(length=30), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('is_weighed', sa.Boolean(), nullable=False),
    sa.Column('is_second_price_sale', sa.Boolean(), nullable=False),
    sa.Column('is_custom_price_sale', sa.Boolean(), nullable=False),
    sa.Column('is_returned', sa.Boolean(), nullable=False),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('is_error_corrected', sa.Boolean(), nullable=False),
    sa.Column('loyalty_points', sa.Float(), nullable=False),
    sa.Column('markdown_amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ej_transaction_id'], ['ej_transactions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'ej_plu_object_id', name='uq_ej_pluobject_site')
    )
    op.create_index('ix_ej_li_date', 'ej_line_items', ['transaction_date'], unique=False)
    op.create_index('ix_ej_li_dept', 'ej_line_items', ['department_number'], unique=False)
    op.create_index('ix_ej_li_site', 'ej_line_items', ['site_id'], unique=False)
    op.create_index('ix_ej_li_tenant', 'ej_line_items', ['tenant_id'], unique=False)
    op.create_index('ix_ej_li_trans', 'ej_line_items', ['ej_transaction_id'], unique=False)
    op.create_index('ix_ej_li_voided', 'ej_line_items', ['is_voided'], unique=False)
    op.create_table('ej_security_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ej_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('ej_header_id', sa.Integer(), nullable=True),
    sa.Column('ej_plu_object_id', sa.Integer(), nullable=True),
    sa.Column('transaction_number', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('register_number', sa.Integer(), nullable=False),
    sa.Column('clerk_number', sa.Integer(), nullable=False),
    sa.Column('clerk_name', sa.String(length=30), nullable=False),
    sa.Column('clerk_shift_id', sa.Integer(), nullable=False),
    sa.Column('sale_total', sa.Float(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ej_transaction_id'], ['ej_transactions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ej_sec_date', 'ej_security_events', ['transaction_date'], unique=False)
    op.create_index('ix_ej_sec_ejhdr', 'ej_security_events', ['ej_header_id'], unique=False)
    op.create_index('ix_ej_sec_site', 'ej_security_events', ['site_id'], unique=False)
    op.create_index('ix_ej_sec_tenant', 'ej_security_events', ['tenant_id'], unique=False)
    op.create_index('ix_ej_sec_type', 'ej_security_events', ['event_type'], unique=False)
    op.create_table('ej_tenders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ej_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('ej_tender_object_id', sa.Integer(), nullable=False),
    sa.Column('ej_detail_id', sa.Integer(), nullable=False),
    sa.Column('tender_number', sa.Integer(), nullable=False),
    sa.Column('tender_type_id', sa.Integer(), nullable=False),
    sa.Column('tender_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('eftpos_card_code', sa.String(length=20), nullable=True),
    sa.Column('eftpos_card_number', sa.String(length=16), nullable=True),
    sa.Column('eftpos_account_type_id', sa.Integer(), nullable=True),
    sa.Column('eftpos_account_type', sa.String(length=30), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('currency_rate', sa.Float(), nullable=True),
    sa.Column('currency_sales_amount', sa.Float(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_account_charge', sa.Boolean(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=True),
    sa.Column('loyalty_card_number', sa.String(length=12), nullable=True),
    sa.Column('cheque_bsb', sa.String(length=30), nullable=True),
    sa.Column('cheque_account', sa.String(length=30), nullable=True),
    sa.Column('cheque_number', sa.String(length=20), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ej_transaction_id'], ['ej_transactions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'ej_tender_object_id', name='uq_ej_tender_site')
    )
    op.create_index('ix_ej_tender_site', 'ej_tenders', ['site_id'], unique=False)
    op.create_index('ix_ej_tender_tenant', 'ej_tenders', ['tenant_id'], unique=False)
    op.create_index('ix_ej_tender_trans', 'ej_tenders', ['ej_transaction_id'], unique=False)
    op.create_index('ix_ej_tender_type', 'ej_tenders', ['tender_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ej_tender_type', table_name='ej_tenders')
    op.drop_index('ix_ej_tender_trans', table_name='ej_tenders')
    op.drop_index('ix_ej_tender_tenant', table_name='ej_tenders')
    op.drop_index('ix_ej_tender_site', table_name='ej_tenders')
    op.drop_table('ej_tenders')
    op.drop_index('ix_ej_sec_type', table_name='ej_security_events')
    op.drop_index('ix_ej_sec_tenant', table_name='ej_security_events')
    op.drop_index('ix_ej_sec_site', table_name='ej_security_events')
    op.drop_index('ix_ej_sec_ejhdr', table_name='ej_security_events')
    op.drop_index('ix_ej_sec_date', table_name='ej_security_events')
    op.drop_table('ej_security_events')
    op.drop_index('ix_ej_li_voided', table_name='ej_line_items')
    op.drop_index('ix_ej_li_trans', table_name='ej_line_items')
    op.drop_index('ix_ej_li_tenant', table_name='ej_line_items')
    op.drop_index('ix_ej_li_site', table_name='ej_line_items')
    op.drop_index('ix_ej_li_dept', table_name='ej_line_items')
    op.drop_index('ix_ej_li_date', table_name='ej_line_items')
    op.drop_table('ej_line_items')
    op.drop_index('ix_ej_disc_trans', table_name='ej_discounts')
    op.drop_index('ix_ej_disc_tenant', table_name='ej_discounts')
    op.drop_table('ej_discounts')
    op.drop_index('ix_hourly_tenant', table_name='site_hourly_summaries')
    op.drop_table('site_hourly_summaries')
    op.drop_index('ix_heartbeats_site_tier', table_name='site_heartbeats')
    op.drop_index('ix_heartbeats_lastseen', table_name='site_heartbeats')
    op.drop_table('site_heartbeats')
    op.drop_index('ix_summary_tenant', table_name='site_daily_summaries')
    op.drop_index('ix_summary_site', table_name='site_daily_summaries')
    op.drop_index('ix_summary_date', table_name='site_daily_summaries')
    op.drop_table('site_daily_summaries')
    op.drop_table('site_api_keys')
    op.drop_index('ix_ej_trans_type', table_name='ej_transactions')
    op.drop_index('ix_ej_trans_tenant', table_name='ej_transactions')
    op.drop_index('ix_ej_trans_site', table_name='ej_transactions')
    op.drop_index('ix_ej_trans_date', table_name='ej_transactions')
    op.drop_table('ej_transactions')
    op.drop_table('data_watermarks')
    op.drop_index('ix_panels_tenant', table_name='dashboard_panels')
    op.drop_table('dashboard_panels')
    op.drop_index('ix_audit_tenant', table_name='audit_log')
    op.drop_index('ix_audit_date', table_name='audit_log')
    op.drop_index('ix_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_tenant', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('user_roles')
    op.drop_table('usage_snapshots')
    op.drop_table('tenant_themes')
    op.drop_index('ix_sites_tenant', table_name='sites')
    op.drop_table('sites')
    op.drop_table('tenants')
    op.drop_table('panel_types')
    # ### end Alembic commands ###
