"""fix_key_prefix_length

Revision ID: 72c912b31dc4
Revises: 1010165eabfa
Create Date: 2026-07-20 18:54:21.786179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c912b31dc4'
down_revision: Union[str, Sequence[str], None] = '1010165eabfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_api_keys', 'key_prefix',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
